version: '2'
services:
  mysql:
    image: mysql:5.7
#    ports:
#      - "3306:3306"
  redis:
    image: redis:5.0
    ports:
      - "6379:6379"
  nodejs:
    image: node:16
  myproject:
    build: .

#  nacos:
#    image: bolingcavalry/nacosserver:0.0.1
#    container_name: nacos
#    restart: always
#    ports:
#      - '8848:8848'
#  provider:
#    image: bolingcavalry/nacossimpleprovider:1.0-SNAPSHOT
#    links:
#      - nacos:nacoshost
#    depends_on:
#      - nacos
#    restart: always
#  consumer:
#    image: bolingcavalry/nacossimpleconsumer:1.0-SNAPSHOT
#    links:
#      - nacos:nacoshost
#    container_name: consumer
#    depends_on:
#      - nacos
#    ports:
#      - '8080:8080'
#    restart: always
